// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Silksong_Rando_Logic_Manager.Data;

#nullable disable

namespace Silksong_Rando_Logic_Manager.Data.Migrations
{
    [DbContext(typeof(LogicDbContext))]
    [Migration("20260809060221_DefaultNewVerificationToUnknown")]
    partial class DefaultNewVerificationToUnknown
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.CheckLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AnnotationSceneUnitX")
                        .HasColumnType("REAL");

                    b.Property<double?>("AnnotationSceneUnitY")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ArchivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableAnnotation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InGameId")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<double?>("InGamePositionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("InGamePositionY")
                        .HasColumnType("REAL");

                    b.Property<double?>("InGamePositionZ")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsIncludedInApworld")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsTodo")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LocalPositionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("LocalPositionY")
                        .HasColumnType("REAL");

                    b.Property<double?>("LocalPositionZ")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedSubroomId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubroomReferenceText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedSubroomId");

                    b.HasIndex("RoomId");

                    b.ToTable("CheckLocations");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InGameId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<double?>("MapUnitMaxX")
                        .HasColumnType("REAL");

                    b.Property<double?>("MapUnitMaxY")
                        .HasColumnType("REAL");

                    b.Property<double?>("MapUnitMinX")
                        .HasColumnType("REAL");

                    b.Property<double?>("MapUnitMinY")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InGameId")
                        .IsUnique();

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.MapChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CacheIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitialState")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MapSceneId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MapUnitMaxX")
                        .HasColumnType("REAL");

                    b.Property<double?>("MapUnitMaxY")
                        .HasColumnType("REAL");

                    b.Property<double?>("MapUnitMinX")
                        .HasColumnType("REAL");

                    b.Property<double?>("MapUnitMinY")
                        .HasColumnType("REAL");

                    b.Property<double?>("MapUnitZ")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MapSceneId", "CacheIndex")
                        .IsUnique();

                    b.ToTable("MapChunks");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.MapOverlay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("BottomOffsetPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageAssetKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("LeftOffsetPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<Guid>("MapId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ScaleXPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(100.0);

                    b.Property<double>("ScaleYPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(100.0);

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("MapOverlays");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.MapScene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InGameId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("MapZoneId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedRoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomReferenceText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedRoomId");

                    b.HasIndex("MapZoneId", "InGameId")
                        .IsUnique();

                    b.ToTable("MapScenes");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.MapZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InGameId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("MapId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MapUnitMaxX")
                        .HasColumnType("REAL");

                    b.Property<double?>("MapUnitMaxY")
                        .HasColumnType("REAL");

                    b.Property<double?>("MapUnitMinX")
                        .HasColumnType("REAL");

                    b.Property<double?>("MapUnitMinY")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MapId", "InGameId")
                        .IsUnique();

                    b.ToTable("MapZones");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InGameId")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSceneImageStale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid?>("RoomGroupId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SceneImagePanXPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("SceneImagePanYPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("SceneImageScaleXPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("SceneImageScaleYPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("SceneUnitHeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("SceneUnitWidth")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomGroupId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RoomGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedMapZoneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneReferenceText")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedMapZoneId");

                    b.ToTable("RoomGroups");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RoomTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AnnotationSceneUnitX")
                        .HasColumnType("REAL");

                    b.Property<double?>("AnnotationSceneUnitY")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ArchivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationRoomReferenceText")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationTransitionAliasText")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InGameId")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<double?>("InGamePositionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("InGamePositionY")
                        .HasColumnType("REAL");

                    b.Property<double?>("InGamePositionZ")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTodo")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LocalPositionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("LocalPositionY")
                        .HasColumnType("REAL");

                    b.Property<double?>("LocalPositionZ")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedDestinationRoomId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedDestinationTransitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedSourceSubroomId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSubroomReferenceText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedDestinationRoomId");

                    b.HasIndex("ResolvedDestinationTransitionId");

                    b.HasIndex("ResolvedSourceSubroomId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomTransitions");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.Subroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SceneUnitHeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("SceneUnitWidth")
                        .HasColumnType("REAL");

                    b.Property<double?>("SceneUnitX")
                        .HasColumnType("REAL");

                    b.Property<double?>("SceneUnitY")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Subrooms");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.SubroomConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationSubroomReferenceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableAnnotation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTodo")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedDestinationSubroomId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedSourceSubroomId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SceneUnitX")
                        .HasColumnType("REAL");

                    b.Property<double?>("SceneUnitY")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSubroomReferenceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedDestinationSubroomId");

                    b.HasIndex("ResolvedSourceSubroomId");

                    b.HasIndex("RoomId");

                    b.ToTable("SubroomConnections");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.CheckLocation", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Subroom", "ResolvedSubroom")
                        .WithMany()
                        .HasForeignKey("ResolvedSubroomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Room", "Room")
                        .WithMany("CheckLocations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResolvedSubroom");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.MapChunk", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.MapScene", "MapScene")
                        .WithMany("Chunks")
                        .HasForeignKey("MapSceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MapScene");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.MapOverlay", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Map", "Map")
                        .WithMany("Overlays")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.MapScene", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.MapZone", "MapZone")
                        .WithMany("Scenes")
                        .HasForeignKey("MapZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Room", "ResolvedRoom")
                        .WithMany()
                        .HasForeignKey("ResolvedRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MapZone");

                    b.Navigation("ResolvedRoom");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.MapZone", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Map", "Map")
                        .WithMany("Zones")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.Room", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.RoomGroup", "RoomGroup")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RoomGroup");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RoomGroup", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.MapZone", "ResolvedMapZone")
                        .WithMany()
                        .HasForeignKey("ResolvedMapZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ResolvedMapZone");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RoomTransition", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Room", "ResolvedDestinationRoom")
                        .WithMany()
                        .HasForeignKey("ResolvedDestinationRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silksong_Rando_Logic_Manager.Data.RoomTransition", "ResolvedDestinationTransition")
                        .WithMany()
                        .HasForeignKey("ResolvedDestinationTransitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Subroom", "ResolvedSourceSubroom")
                        .WithMany()
                        .HasForeignKey("ResolvedSourceSubroomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Room", "Room")
                        .WithMany("Transitions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResolvedDestinationRoom");

                    b.Navigation("ResolvedDestinationTransition");

                    b.Navigation("ResolvedSourceSubroom");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.Subroom", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Room", "Room")
                        .WithMany("Subrooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.SubroomConnection", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Subroom", "ResolvedDestinationSubroom")
                        .WithMany()
                        .HasForeignKey("ResolvedDestinationSubroomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Subroom", "ResolvedSourceSubroom")
                        .WithMany()
                        .HasForeignKey("ResolvedSourceSubroomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Room", "Room")
                        .WithMany("Connections")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResolvedDestinationSubroom");

                    b.Navigation("ResolvedSourceSubroom");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.Map", b =>
                {
                    b.Navigation("Overlays");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.MapScene", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.MapZone", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.Room", b =>
                {
                    b.Navigation("CheckLocations");

                    b.Navigation("Connections");

                    b.Navigation("Subrooms");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RoomGroup", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
