// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Silksong_Rando_Logic_Manager.Data;

#nullable disable

namespace Silksong_Rando_Logic_Manager.Data.Migrations
{
    [DbContext(typeof(LogicDbContext))]
    [Migration("20260805080622_AddRoomSceneBounds")]
    partial class AddRoomSceneBounds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.CheckLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApworldLocationReferenceText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InGameId")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsIncludedInApworld")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsTodo")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<double?>("LocalPositionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("LocalPositionY")
                        .HasColumnType("REAL");

                    b.Property<double?>("LocalPositionZ")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedSubroomId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubroomReferenceText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("WorldPositionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("WorldPositionY")
                        .HasColumnType("REAL");

                    b.Property<double?>("WorldPositionZ")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedSubroomId");

                    b.HasIndex("RoomId");

                    b.ToTable("CheckLocations");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.GameMapConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GameMapBottom")
                        .HasColumnType("REAL");

                    b.Property<double?>("GameMapLeft")
                        .HasColumnType("REAL");

                    b.Property<double?>("GameMapRight")
                        .HasColumnType("REAL");

                    b.Property<double?>("GameMapTop")
                        .HasColumnType("REAL");

                    b.Property<double?>("SceneToMapScale")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameMapConfigurations");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.MapImageCalibration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<double?>("MapHeightScalePercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(100.0);

                    b.Property<double?>("MapOffsetXPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double?>("MapOffsetYPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.HasKey("Id");

                    b.HasIndex("ImageKey")
                        .IsUnique();

                    b.ToTable("MapImageCalibrations");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InGameId")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<double?>("MapCoordinateX")
                        .HasColumnType("REAL");

                    b.Property<double?>("MapCoordinateY")
                        .HasColumnType("REAL");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid?>("RoomGroupId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SceneBoundsMaxX")
                        .HasColumnType("REAL");

                    b.Property<double?>("SceneBoundsMaxY")
                        .HasColumnType("REAL");

                    b.Property<double?>("SceneBoundsMinX")
                        .HasColumnType("REAL");

                    b.Property<double?>("SceneBoundsMinY")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomGroupId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RoomGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoomGroups");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RoomMapCoordinate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("MapX")
                        .HasColumnType("REAL");

                    b.Property<double>("MapY")
                        .HasColumnType("REAL");

                    b.Property<string>("SceneName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("SceneName")
                        .IsUnique();

                    b.ToTable("RoomMapCoordinates");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RoomTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationRoomReferenceText")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationTransitionAliasText")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InGameId")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTodo")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<double?>("LocalPositionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("LocalPositionY")
                        .HasColumnType("REAL");

                    b.Property<double?>("LocalPositionZ")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedDestinationRoomId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedDestinationTransitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedSourceSubroomId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSubroomReferenceText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("WorldPositionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("WorldPositionY")
                        .HasColumnType("REAL");

                    b.Property<double?>("WorldPositionZ")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedDestinationRoomId");

                    b.HasIndex("ResolvedDestinationTransitionId");

                    b.HasIndex("ResolvedSourceSubroomId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomTransitions");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.Subroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Subrooms");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.SubroomConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationSubroomReferenceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTodo")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedDestinationSubroomId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedSourceSubroomId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSubroomReferenceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedDestinationSubroomId");

                    b.HasIndex("ResolvedSourceSubroomId");

                    b.HasIndex("RoomId");

                    b.ToTable("SubroomConnections");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.CheckLocation", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Subroom", "ResolvedSubroom")
                        .WithMany()
                        .HasForeignKey("ResolvedSubroomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Room", "Room")
                        .WithMany("CheckLocations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResolvedSubroom");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.Room", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.RoomGroup", "RoomGroup")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RoomGroup");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RoomTransition", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Room", "ResolvedDestinationRoom")
                        .WithMany()
                        .HasForeignKey("ResolvedDestinationRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silksong_Rando_Logic_Manager.Data.RoomTransition", "ResolvedDestinationTransition")
                        .WithMany()
                        .HasForeignKey("ResolvedDestinationTransitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Subroom", "ResolvedSourceSubroom")
                        .WithMany()
                        .HasForeignKey("ResolvedSourceSubroomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Room", "Room")
                        .WithMany("Transitions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResolvedDestinationRoom");

                    b.Navigation("ResolvedDestinationTransition");

                    b.Navigation("ResolvedSourceSubroom");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.Subroom", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Room", "Room")
                        .WithMany("Subrooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.SubroomConnection", b =>
                {
                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Subroom", "ResolvedDestinationSubroom")
                        .WithMany()
                        .HasForeignKey("ResolvedDestinationSubroomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Subroom", "ResolvedSourceSubroom")
                        .WithMany()
                        .HasForeignKey("ResolvedSourceSubroomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silksong_Rando_Logic_Manager.Data.Room", "Room")
                        .WithMany("Connections")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResolvedDestinationSubroom");

                    b.Navigation("ResolvedSourceSubroom");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.Room", b =>
                {
                    b.Navigation("CheckLocations");

                    b.Navigation("Connections");

                    b.Navigation("Subrooms");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RoomGroup", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
