// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Silksong_Rando_Logic_Manager.Data;

#nullable disable

namespace Silksong_Rando_Logic_Manager.Data.Migrations;

[DbContext(typeof(LogicDbContext))]
[Migration("20260905120000_AddRequirementCatalogue")]
partial class AddRequirementCatalogue
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

        modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RequirementItem", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
            b.Property<string>("Category").HasColumnType("TEXT");
            b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
            b.Property<string>("Notes").IsRequired().HasColumnType("TEXT");
            b.Property<string>("OutputValue").IsRequired().HasColumnType("TEXT");
            b.Property<int>("SortOrder").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.ToTable("RequirementItems");
        });

        modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RequirementItemAlias", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
            b.Property<string>("Alias").IsRequired().HasColumnType("TEXT");
            b.Property<Guid>("RequirementItemId").HasColumnType("TEXT");
            b.Property<int>("SortOrder").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.HasIndex("RequirementItemId");
            b.ToTable("RequirementItemAliases");
        });

        modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RequirementPredicate", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
            b.Property<string>("Category").HasColumnType("TEXT");
            b.Property<string>("InputSyntax").IsRequired().HasColumnType("TEXT");
            b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
            b.Property<string>("Notes").IsRequired().HasColumnType("TEXT");
            b.Property<string>("OutputSyntax").IsRequired().HasColumnType("TEXT");
            b.Property<int>("SortOrder").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.ToTable("RequirementPredicates");
        });

        modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RequirementPredicateAlias", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
            b.Property<string>("Alias").IsRequired().HasColumnType("TEXT");
            b.Property<Guid>("RequirementPredicateId").HasColumnType("TEXT");
            b.Property<int>("SortOrder").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.HasIndex("RequirementPredicateId");
            b.ToTable("RequirementPredicateAliases");
        });

        modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RequirementItemAlias", b =>
        {
            b.HasOne("Silksong_Rando_Logic_Manager.Data.RequirementItem", "RequirementItem")
                .WithMany("Aliases")
                .HasForeignKey("RequirementItemId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("RequirementItem");
        });

        modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RequirementPredicateAlias", b =>
        {
            b.HasOne("Silksong_Rando_Logic_Manager.Data.RequirementPredicate", "RequirementPredicate")
                .WithMany("Aliases")
                .HasForeignKey("RequirementPredicateId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("RequirementPredicate");
        });

        modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RequirementItem", b => b.Navigation("Aliases"));
        modelBuilder.Entity("Silksong_Rando_Logic_Manager.Data.RequirementPredicate", b => b.Navigation("Aliases"));
#pragma warning restore 612, 618
    }
}
