using Silksong_Rando_Logic_Manager.Data;

namespace Silksong_Rando_Logic_Manager.Services;

// These mappers intentionally list fields rather than deriving them from CLR
// properties. Resolver IDs and lifecycle fields are never ordinary write fields.
public sealed class SubroomFieldDiffMapper : ChildMapper<Subroom>
{
    public override IReadOnlyList<string> EditableFields { get; } = [nameof(Subroom.FriendlyName), nameof(Subroom.ReferenceId), nameof(Subroom.Notes), nameof(Subroom.SceneUnitX), nameof(Subroom.SceneUnitY), nameof(Subroom.SceneUnitWidth), nameof(Subroom.SceneUnitHeight)];
    protected override object? Get(Subroom x, string f) => f switch { nameof(Subroom.FriendlyName) => x.FriendlyName, nameof(Subroom.ReferenceId) => x.ReferenceId, nameof(Subroom.Notes) => x.Notes, nameof(Subroom.SceneUnitX) => x.SceneUnitX, nameof(Subroom.SceneUnitY) => x.SceneUnitY, nameof(Subroom.SceneUnitWidth) => x.SceneUnitWidth, nameof(Subroom.SceneUnitHeight) => x.SceneUnitHeight, _ => throw new ArgumentOutOfRangeException(nameof(f)) };
    protected override void Set(Subroom x, string f, object? v) { switch (f) { case nameof(Subroom.FriendlyName): x.FriendlyName=(string)v!; break; case nameof(Subroom.ReferenceId): x.ReferenceId=(string)v!; break; case nameof(Subroom.Notes): x.Notes=(string)v!; break; case nameof(Subroom.SceneUnitX): x.SceneUnitX=(double?)v; break; case nameof(Subroom.SceneUnitY): x.SceneUnitY=(double?)v; break; case nameof(Subroom.SceneUnitWidth): x.SceneUnitWidth=(double?)v; break; case nameof(Subroom.SceneUnitHeight): x.SceneUnitHeight=(double?)v; break; default: throw new ArgumentOutOfRangeException(nameof(f)); } }
    public override Subroom Clone(Subroom x) => new() { Id=x.Id, RoomId=x.RoomId, FriendlyName=x.FriendlyName, ReferenceId=x.ReferenceId, Notes=x.Notes, SceneUnitX=x.SceneUnitX, SceneUnitY=x.SceneUnitY, SceneUnitWidth=x.SceneUnitWidth, SceneUnitHeight=x.SceneUnitHeight, SortOrder=x.SortOrder, IsArchived=x.IsArchived, ArchivedUtc=x.ArchivedUtc, CreatedUtc=x.CreatedUtc, UpdatedUtc=x.UpdatedUtc };
}

public sealed class ConnectionFieldDiffMapper : ChildMapper<SubroomConnection>
{
    public override IReadOnlyList<string> EditableFields { get; } = [nameof(SubroomConnection.Alias), nameof(SubroomConnection.FriendlyName), nameof(SubroomConnection.SourceSubroomReferenceText), nameof(SubroomConnection.DestinationSubroomReferenceText), nameof(SubroomConnection.Requirements), nameof(SubroomConnection.Notes), nameof(SubroomConnection.EnableAnnotation), nameof(SubroomConnection.SceneUnitX), nameof(SubroomConnection.SceneUnitY), nameof(SubroomConnection.IsTodo), nameof(SubroomConnection.IsVerified)];
    protected override object? Get(SubroomConnection x,string f)=>f switch { nameof(SubroomConnection.Alias)=>x.Alias,nameof(SubroomConnection.FriendlyName)=>x.FriendlyName,nameof(SubroomConnection.SourceSubroomReferenceText)=>x.SourceSubroomReferenceText,nameof(SubroomConnection.DestinationSubroomReferenceText)=>x.DestinationSubroomReferenceText,nameof(SubroomConnection.Requirements)=>x.Requirements,nameof(SubroomConnection.Notes)=>x.Notes,nameof(SubroomConnection.EnableAnnotation)=>x.EnableAnnotation,nameof(SubroomConnection.SceneUnitX)=>x.SceneUnitX,nameof(SubroomConnection.SceneUnitY)=>x.SceneUnitY,nameof(SubroomConnection.IsTodo)=>x.IsTodo,nameof(SubroomConnection.IsVerified)=>x.IsVerified,_=>throw new ArgumentOutOfRangeException(nameof(f))};
    protected override void Set(SubroomConnection x,string f,object? v) { switch(f) { case nameof(SubroomConnection.Alias):x.Alias=(string)v!;break;case nameof(SubroomConnection.FriendlyName):x.FriendlyName=(string)v!;break;case nameof(SubroomConnection.SourceSubroomReferenceText):x.SourceSubroomReferenceText=(string)v!;break;case nameof(SubroomConnection.DestinationSubroomReferenceText):x.DestinationSubroomReferenceText=(string)v!;break;case nameof(SubroomConnection.Requirements):x.Requirements=(string)v!;break;case nameof(SubroomConnection.Notes):x.Notes=(string)v!;break;case nameof(SubroomConnection.EnableAnnotation):x.EnableAnnotation=(bool)v!;break;case nameof(SubroomConnection.SceneUnitX):x.SceneUnitX=(double?)v;break;case nameof(SubroomConnection.SceneUnitY):x.SceneUnitY=(double?)v;break;case nameof(SubroomConnection.IsTodo):x.IsTodo=(bool)v!;break;case nameof(SubroomConnection.IsVerified):x.IsVerified=(bool?)v;break;default:throw new ArgumentOutOfRangeException(nameof(f));}}
    public override SubroomConnection Clone(SubroomConnection x)=>new(){Id=x.Id,RoomId=x.RoomId,Alias=x.Alias,FriendlyName=x.FriendlyName,SourceSubroomReferenceText=x.SourceSubroomReferenceText,DestinationSubroomReferenceText=x.DestinationSubroomReferenceText,Requirements=x.Requirements,RequirementsParseSucceeded=x.RequirementsParseSucceeded,Notes=x.Notes,EnableAnnotation=x.EnableAnnotation,SceneUnitX=x.SceneUnitX,SceneUnitY=x.SceneUnitY,ResolvedSourceSubroomId=x.ResolvedSourceSubroomId,ResolvedDestinationSubroomId=x.ResolvedDestinationSubroomId,SortOrder=x.SortOrder,IsTodo=x.IsTodo,IsVerified=x.IsVerified,IsArchived=x.IsArchived,ArchivedUtc=x.ArchivedUtc,CreatedUtc=x.CreatedUtc,UpdatedUtc=x.UpdatedUtc};
    protected override void CopyDerived(SubroomConnection target, SubroomConnection committed) => target.RequirementsParseSucceeded=committed.RequirementsParseSucceeded;
    protected override void CopyResolver(SubroomConnection target, SubroomConnection committed) { target.ResolvedSourceSubroomId=committed.ResolvedSourceSubroomId; target.ResolvedDestinationSubroomId=committed.ResolvedDestinationSubroomId; }
}

public sealed class CheckFieldDiffMapper : ChildMapper<CheckLocation>
{
    public override IReadOnlyList<string> EditableFields { get; } = [nameof(CheckLocation.FriendlyName),nameof(CheckLocation.InGameId),nameof(CheckLocation.InGamePositionX),nameof(CheckLocation.InGamePositionY),nameof(CheckLocation.InGamePositionZ),nameof(CheckLocation.LocalPositionX),nameof(CheckLocation.LocalPositionY),nameof(CheckLocation.LocalPositionZ),nameof(CheckLocation.AnnotationSceneUnitX),nameof(CheckLocation.AnnotationSceneUnitY),nameof(CheckLocation.SubroomReferenceText),nameof(CheckLocation.Requirements),nameof(CheckLocation.Notes),nameof(CheckLocation.LocationType),nameof(CheckLocation.EnableAnnotation),nameof(CheckLocation.IsTodo),nameof(CheckLocation.IsVerified)];
    protected override object? Get(CheckLocation x,string f)=>f switch { nameof(CheckLocation.FriendlyName)=>x.FriendlyName,nameof(CheckLocation.InGameId)=>x.InGameId,nameof(CheckLocation.InGamePositionX)=>x.InGamePositionX,nameof(CheckLocation.InGamePositionY)=>x.InGamePositionY,nameof(CheckLocation.InGamePositionZ)=>x.InGamePositionZ,nameof(CheckLocation.LocalPositionX)=>x.LocalPositionX,nameof(CheckLocation.LocalPositionY)=>x.LocalPositionY,nameof(CheckLocation.LocalPositionZ)=>x.LocalPositionZ,nameof(CheckLocation.AnnotationSceneUnitX)=>x.AnnotationSceneUnitX,nameof(CheckLocation.AnnotationSceneUnitY)=>x.AnnotationSceneUnitY,nameof(CheckLocation.SubroomReferenceText)=>x.SubroomReferenceText,nameof(CheckLocation.Requirements)=>x.Requirements,nameof(CheckLocation.Notes)=>x.Notes,nameof(CheckLocation.LocationType)=>x.LocationType,nameof(CheckLocation.EnableAnnotation)=>x.EnableAnnotation,nameof(CheckLocation.IsTodo)=>x.IsTodo,nameof(CheckLocation.IsVerified)=>x.IsVerified,_=>throw new ArgumentOutOfRangeException(nameof(f))};
    protected override void Set(CheckLocation x,string f,object? v) { switch(f) { case nameof(CheckLocation.FriendlyName):x.FriendlyName=(string)v!;break;case nameof(CheckLocation.InGameId):x.InGameId=(string?)v;break;case nameof(CheckLocation.InGamePositionX):x.InGamePositionX=(double?)v;break;case nameof(CheckLocation.InGamePositionY):x.InGamePositionY=(double?)v;break;case nameof(CheckLocation.InGamePositionZ):x.InGamePositionZ=(double?)v;break;case nameof(CheckLocation.LocalPositionX):x.LocalPositionX=(double?)v;break;case nameof(CheckLocation.LocalPositionY):x.LocalPositionY=(double?)v;break;case nameof(CheckLocation.LocalPositionZ):x.LocalPositionZ=(double?)v;break;case nameof(CheckLocation.AnnotationSceneUnitX):x.AnnotationSceneUnitX=(double?)v;break;case nameof(CheckLocation.AnnotationSceneUnitY):x.AnnotationSceneUnitY=(double?)v;break;case nameof(CheckLocation.SubroomReferenceText):x.SubroomReferenceText=(string?)v;break;case nameof(CheckLocation.Requirements):x.Requirements=(string)v!;break;case nameof(CheckLocation.Notes):x.Notes=(string)v!;break;case nameof(CheckLocation.LocationType):x.LocationType=(string?)v;break;case nameof(CheckLocation.EnableAnnotation):x.EnableAnnotation=(bool)v!;break;case nameof(CheckLocation.IsTodo):x.IsTodo=(bool)v!;break;case nameof(CheckLocation.IsVerified):x.IsVerified=(bool?)v;break;default:throw new ArgumentOutOfRangeException(nameof(f));}}
    public override CheckLocation Clone(CheckLocation x)=>new(){Id=x.Id,RoomId=x.RoomId,FriendlyName=x.FriendlyName,InGameId=x.InGameId,InGamePositionX=x.InGamePositionX,InGamePositionY=x.InGamePositionY,InGamePositionZ=x.InGamePositionZ,LocalPositionX=x.LocalPositionX,LocalPositionY=x.LocalPositionY,LocalPositionZ=x.LocalPositionZ,AnnotationSceneUnitX=x.AnnotationSceneUnitX,AnnotationSceneUnitY=x.AnnotationSceneUnitY,SubroomReferenceText=x.SubroomReferenceText,Requirements=x.Requirements,RequirementsParseSucceeded=x.RequirementsParseSucceeded,Notes=x.Notes,LocationType=x.LocationType,EnableAnnotation=x.EnableAnnotation,ResolvedSubroomId=x.ResolvedSubroomId,SortOrder=x.SortOrder,IsTodo=x.IsTodo,IsVerified=x.IsVerified,IsArchived=x.IsArchived,ArchivedUtc=x.ArchivedUtc,CreatedUtc=x.CreatedUtc,UpdatedUtc=x.UpdatedUtc};
    protected override void CopyDerived(CheckLocation target,CheckLocation committed)=>target.RequirementsParseSucceeded=committed.RequirementsParseSucceeded;
    protected override void CopyResolver(CheckLocation target,CheckLocation committed)=>target.ResolvedSubroomId=committed.ResolvedSubroomId;
}

public abstract class ChildMapper<T> : IChildRowFieldDiffMapper<T> where T : ArchivableEntity
{
    public abstract IReadOnlyList<string> EditableFields { get; }
    public abstract T Clone(T value);
    protected abstract object? Get(T value,string field); protected abstract void Set(T value,string field,object? source);
    protected virtual void CopyDerived(T target,T committed) { }
    protected virtual void CopyResolver(T target,T committed) { }
    public IReadOnlyList<string> Differences(T baseline,T draft)=>EditableFields.Where(f=>!Equals(Get(baseline,f),Get(draft,f))).ToArray();
    public void Apply(T target,T source,IEnumerable<string> fields) { foreach(var f in fields) Set(target,f,Get(source,f)); }
    public void Reconcile(T live,T committed,T request,IReadOnlyCollection<string> fields,bool resolved) { foreach(var f in fields) if(Equals(Get(live,f),Get(request,f))) Set(live,f,Get(committed,f)); live.UpdatedUtc=committed.UpdatedUtc; CopyDerived(live,committed); if(resolved) CopyResolver(live,committed); }
}
